# Generated by Django 5.2.10 on 2026-01-26 01:43

import django.utils.timezone
from django.db import migrations, models


def migrate_roles_forward(apps, schema_editor):
    """نسخ بيانات الأدوار القديمة للحقول الجديدة"""
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.all():
        old_name = role.role_name
        if old_name == 'Admin':
            role.code = 'admin'
            role.display_name = 'مدير النظام'
            role.is_system = True
        elif old_name == 'Instructor':
            role.code = 'instructor'
            role.display_name = 'مدرس'
            role.is_system = True
        elif old_name == 'Student':
            role.code = 'student'
            role.display_name = 'طالب'
            role.is_system = True
        else:
            # دور مخصص
            role.code = old_name.lower().replace(' ', '_')
            role.display_name = old_name
            role.is_system = False
        role.save()


def migrate_permissions_forward(apps, schema_editor):
    """نسخ بيانات الصلاحيات القديمة للحقول الجديدة"""
    Permission = apps.get_model('accounts', 'Permission')
    counter = 1
    for perm in Permission.objects.all():
        old_name = perm.permission_name
        # تحويل الاسم القديم لكود
        perm.code = old_name if old_name else f'perm_{counter}'
        perm.display_name = old_name if old_name else f'صلاحية {counter}'
        perm.category = 'system'
        counter += 1
        perm.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # === الخطوة 1: إضافة الحقول الجديدة (nullable أولاً) ===
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="كود الدور",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name",
            field=models.CharField(
                max_length=100,
                null=True,
                verbose_name="اسم العرض",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="دور نظام"),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        
        migrations.AddField(
            model_name="permission",
            name="code",
            field=models.CharField(
                max_length=100,
                null=True,
                verbose_name="كود الصلاحية",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="display_name",
            field=models.CharField(
                max_length=150,
                null=True,
                verbose_name="اسم العرض",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="category",
            field=models.CharField(
                choices=[
                    ("courses", "المقررات"),
                    ("files", "الملفات"),
                    ("users", "المستخدمين"),
                    ("notifications", "الإشعارات"),
                    ("ai", "الذكاء الاصطناعي"),
                    ("system", "النظام"),
                ],
                default="system",
                max_length=50,
                verbose_name="التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشطة"),
        ),
        migrations.AddField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإنشاء",
            ),
            preserve_default=False,
        ),
        
        # === الخطوة 2: نسخ البيانات ===
        migrations.RunPython(migrate_roles_forward, migrations.RunPython.noop),
        migrations.RunPython(migrate_permissions_forward, migrations.RunPython.noop),
        
        # === الخطوة 3: جعل الحقول الجديدة required و unique ===
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="كود الدور",
                help_text="معرف فريد للدور (بالإنجليزية، مثل: admin, instructor)",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="display_name",
            field=models.CharField(
                max_length=100,
                verbose_name="اسم العرض",
                help_text="الاسم الذي يظهر للمستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="كود الصلاحية",
                help_text="معرف فريد (مثل: manage_files, view_courses)",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="display_name",
            field=models.CharField(
                max_length=150,
                verbose_name="اسم العرض",
                help_text="الاسم الذي يظهر في لوحة التحكم",
            ),
        ),
        
        # === الخطوة 4: حذف الحقول القديمة ===
        migrations.RemoveField(
            model_name="role",
            name="role_name",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="permission_name",
        ),
        
        # === الخطوة 5: تحديث Meta options ===
        migrations.AlterModelOptions(
            name="permission",
            options={
                "ordering": ["category", "display_name"],
                "verbose_name": "صلاحية",
                "verbose_name_plural": "الصلاحيات",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["-is_system", "display_name"],
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
            },
        ),
    ]
