# Generated by Django 5.2.10 on 2026-01-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_enhanced_permissions_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="الأدوار الافتراضية التي لا يمكن حذفها",
                verbose_name="دور نظام",
            ),
        ),
    ]
