# Generated by Django 6.0.2 on 2026-02-08 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['course', 'is_visible'], name='idx_lf_course_vis'),
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['uploader', 'is_deleted'], name='idx_lf_uploader_del'),
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['uploader', 'is_deleted', 'upload_date'], name='idx_lf_upload_stats'),
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['course', 'is_visible', 'is_deleted'], name='idx_lf_crs_vis_del'),
        ),
    ]
