# Generated by Django 5.2.10 on 2026-01-23 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_features", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisummary",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_summary",
                to="courses.lecturefile",
                verbose_name="الملف",
            ),
        ),
        migrations.AlterField(
            model_name="aisummary",
            name="model_used",
            field=models.CharField(
                default="gemini-2.0-flash",
                max_length=100,
                verbose_name="النموذج المستخدم",
            ),
        ),
        migrations.CreateModel(
            name="AIGeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "اختيار من متعدد"),
                            ("true_false", "صح وخطأ"),
                            ("short_answer", "إجابة قصيرة"),
                            ("mixed", "مختلط"),
                        ],
                        default="short_answer",
                        max_length=50,
                        verbose_name="نوع السؤال",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="قائمة الخيارات للأسئلة متعددة الاختيار",
                        null=True,
                    ),
                ),
                ("correct_answer", models.TextField(verbose_name="الإجابة الصحيحة")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, null=True, verbose_name="الشرح / التفسير"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        default="medium", max_length=20, verbose_name="مستوى الصعوبة"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التوليد"
                    ),
                ),
                (
                    "is_cached",
                    models.BooleanField(default=True, verbose_name="مخزن مؤقتاً"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to="courses.lecturefile",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال AI",
                "verbose_name_plural": "أسئلة AI",
                "db_table": "ai_generated_questions",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.DeleteModel(
            name="AIQuestion",
        ),
        migrations.AddIndex(
            model_name="aigeneratedquestion",
            index=models.Index(fields=["file"], name="ai_generate_file_id_bc9b7b_idx"),
        ),
        migrations.AddIndex(
            model_name="aigeneratedquestion",
            index=models.Index(
                fields=["question_type"], name="ai_generate_questio_6ecb08_idx"
            ),
        ),
    ]
