# Generated by Django 6.0.2 on 2026-02-08 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_alter_aisummary_file_alter_aisummary_model_used_and_more'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='score',
            field=models.FloatField(default=1.0, verbose_name='الدرجة'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='md_file_path',
            field=models.CharField(blank=True, help_text='المسار النسبي لملف الملخص في media/', max_length=500, null=True, verbose_name='مسار ملف Markdown'),
        ),
        migrations.AlterField(
            model_name='aichat',
            name='is_helpful',
            field=models.BooleanField(blank=True, null=True, verbose_name='مفيد'),
        ),
        migrations.AlterField(
            model_name='aigeneratedquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='aigeneratedquestion',
            name='options',
            field=models.JSONField(blank=True, help_text='خيارات MCQ', null=True),
        ),
        migrations.AlterField(
            model_name='aigeneratedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_questions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='is_cached',
            field=models.BooleanField(default=True, verbose_name='مخزن مؤقتاً'),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='summary_text',
            field=models.TextField(blank=True, default='', help_text='ملخص مختصر - النص الكامل في ملف .md', verbose_name='نص الملخص'),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_summaries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('summary', 'تلخيص'), ('questions', 'أسئلة'), ('mixed', 'ملخص + أسئلة')], max_length=20, verbose_name='نوع العملية')),
                ('config', models.JSONField(blank=True, default=dict, help_text='تكوين المصفوفة: عدد MCQ, TF, SA مع الدرجات', verbose_name='التكوين')),
                ('user_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المدرس')),
                ('md_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار ملف النتيجة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to='courses.lecturefile', verbose_name='الملف')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'عملية توليد AI',
                'verbose_name_plural': 'عمليات توليد AI',
                'db_table': 'ai_generation_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'created_at'], name='ai_generati_instruc_66b936_idx'), models.Index(fields=['file'], name='ai_generati_file_id_e73c2e_idx'), models.Index(fields=['status'], name='ai_generati_status_339a0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, help_text='0-100', verbose_name='نسبة التقدم')),
                ('last_position', models.CharField(blank=True, default='', help_text='رقم الصفحة أو وقت الفيديو', max_length=100, verbose_name='آخر موقع')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخر وصول')),
                ('total_time_seconds', models.PositiveIntegerField(default=0, verbose_name='إجمالي وقت الدراسة (ثانية)')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lecturefile', verbose_name='الملف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقدم طالب',
                'verbose_name_plural': 'تقدم الطلاب',
                'db_table': 'student_progress',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['student', 'last_accessed'], name='student_pro_student_79cac6_idx')],
                'unique_together': {('student', 'file')},
            },
        ),
    ]
