# Generated by Django 6.0.2 on 2026-02-08 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0003_aigeneratedquestion_score_aisummary_md_file_path_and_more'),
        ('courses', '0002_lecturefile_idx_lf_course_vis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash (سريع)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (متوازن)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (دقيق)'), ('gemini-2.0-pro', 'Gemini 2.0 Pro (متقدم)')], default='gemini-2.0-flash', help_text='نموذج Gemini المستخدم لجميع عمليات AI', max_length=50, verbose_name='النموذج النشط')),
                ('chunk_size', models.PositiveIntegerField(default=30000, help_text='الحد الأقصى لحجم كل جزء من النص قبل الإرسال لـ AI (1000-100000)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)], verbose_name='حجم التقطيع (حرف)')),
                ('chunk_overlap', models.PositiveIntegerField(default=500, help_text='عدد الأحرف المتداخلة بين الأجزاء للحفاظ على السياق', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='تداخل الأجزاء (حرف)')),
                ('max_output_tokens', models.PositiveIntegerField(default=2000, help_text='الحد الأقصى لعدد التوكنات في استجابة AI (100-8192)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(8192)], verbose_name='حد التوكنات للإخراج')),
                ('temperature', models.FloatField(default=0.3, help_text='0.0 = محافظ ودقيق | 1.0 = متوازن | 2.0 = إبداعي', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='درجة الإبداع (Temperature)')),
                ('user_rate_limit_per_hour', models.PositiveIntegerField(default=10, help_text='الحد الأقصى لطلبات AI لكل مستخدم في الساعة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='حد الطلبات/ساعة للمستخدم')),
                ('is_service_enabled', models.BooleanField(default=True, help_text='إيقاف هذا الخيار يعطّل جميع خدمات AI في النظام', verbose_name='خدمة AI مفعلة')),
                ('maintenance_message', models.CharField(blank=True, default='خدمة الذكاء الاصطناعي متوقفة مؤقتاً للصيانة.', help_text='الرسالة التي تظهر للمستخدمين عند تعطيل الخدمة', max_length=500, verbose_name='رسالة الصيانة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_config_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات الذكاء الاصطناعي',
                'verbose_name_plural': 'إعدادات الذكاء الاصطناعي',
                'db_table': 'ai_configuration',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='مفتاح API', help_text='اسم وصفي للتمييز (مثال: مفتاح المشروع الرئيسي)', max_length=100, verbose_name='اسم المفتاح')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (مستقبلي)')], default='gemini', max_length=20, verbose_name='المزود')),
                ('_encrypted_key', models.TextField(db_column='encrypted_key', help_text='يتم التشفير تلقائياً عند الحفظ', verbose_name='المفتاح المشفر')),
                ('key_hint', models.CharField(blank=True, help_text='آخر 4 أحرف من المفتاح (للتعرف)', max_length=20, verbose_name='تلميح المفتاح')),
                ('status', models.CharField(choices=[('active', '🟢 نشط'), ('cooldown', '🟡 في فترة راحة'), ('disabled', '🔴 معطل'), ('error', '⚠️ خطأ')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, help_text='يمكن تعطيله يدوياً من الأدمن', verbose_name='مفعّل')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='آخر خطأ')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر خطأ')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر نجاح')),
                ('last_latency_ms', models.PositiveIntegerField(default=0, verbose_name='زمن الاستجابة (مللي ثانية)')),
                ('rpm_limit', models.PositiveIntegerField(default=15, help_text='الحد الأقصى للطلبات في الدقيقة حسب خطة Google Cloud', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='حد الطلبات/دقيقة (RPM)')),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='المفتاح لن يُستخدم حتى هذا الوقت', null=True, verbose_name='فترة الراحة حتى')),
                ('tokens_used_today', models.PositiveIntegerField(default=0, verbose_name='التوكنات المستخدمة اليوم')),
                ('tokens_reset_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إعادة تعيين')),
                ('priority', models.PositiveIntegerField(default=0, help_text='أقل رقم = أولوية أعلى. يُستخدم لترتيب التدوير', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مفتاح API',
                'verbose_name_plural': 'مفاتيح API',
                'db_table': 'ai_api_keys',
                'ordering': ['priority', '-is_active', 'created_at'],
                'indexes': [models.Index(fields=['provider', 'is_active', 'status'], name='ai_api_keys_provide_0cb026_idx'), models.Index(fields=['cooldown_until'], name='ai_api_keys_cooldow_1336df_idx')],
            },
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='api_key_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_features.apikey', verbose_name='مفتاح API المستخدم'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['request_time'], name='ai_usage_lo_request_949837_idx'),
        ),
    ]
