# Generated by Django 6.0.2 on 2026-02-09 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0004_aiconfiguration_apikey_aiusagelog_api_key_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='active_model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (سريع - مُوصى به)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (متقدم)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (مستقر)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (متوازن)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (دقيق)'), ('gemini-2.0-pro', 'Gemini 2.0 Pro (متقدم)'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview (تجريبي - أسرع)'), ('gemini-3-pro-preview', 'Gemini 3 Pro Preview (تجريبي - ذكاء فائق)')], default='gemini-2.5-flash', help_text='نموذج Gemini المستخدم لجميع عمليات AI', max_length=50, verbose_name='النموذج النشط'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='max_output_tokens',
            field=models.PositiveIntegerField(default=8192, help_text='الحد الأقصى لعدد التوكنات في استجابة AI (100-65536)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(65536)], verbose_name='حد التوكنات للإخراج'),
        ),
    ]
