# Generated by Django 6.0.2 on 2026-02-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0005_alter_aiconfiguration_active_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='active_model',
            field=models.CharField(choices=[('gpt-4.1-mini', 'GPT-4.1 Mini (افتراضي - مُوصى به)'), ('gpt-4.1-nano', 'GPT-4.1 Nano (خفيف وسريع)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (عبر Manus Proxy)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (متقدم - عبر Manus)'), ('gpt-4o', 'GPT-4o (متقدم)'), ('gpt-4o-mini', 'GPT-4o Mini (سريع)')], default='gpt-4.1-mini', help_text='نموذج AI المستخدم لجميع العمليات (عبر Manus API Proxy)', max_length=50, verbose_name='النموذج النشط'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='provider',
            field=models.CharField(choices=[('manus', 'Manus API Proxy (OpenAI Compatible)'), ('openai', 'OpenAI Direct')], default='manus', max_length=20, verbose_name='المزود'),
        ),
    ]
