# Generated by Django 6.0.2 on 2026-02-09 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0002_lecturefile_idx_lf_course_vis_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات البريد الإلكتروني')),
                ('email_file_upload', models.BooleanField(default=True, verbose_name='إشعار رفع ملف جديد')),
                ('email_announcement', models.BooleanField(default=True, verbose_name='إشعار إعلان')),
                ('email_assignment', models.BooleanField(default=True, verbose_name='إشعار واجب')),
                ('email_exam', models.BooleanField(default=True, verbose_name='إشعار اختبار')),
                ('email_grade', models.BooleanField(default=True, verbose_name='إشعار درجة')),
                ('email_system', models.BooleanField(default=True, verbose_name='إشعار نظام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تفضيلات إشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_19df93_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_e4c995_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_course__c5d211_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrecipient',
            name='notificatio_user_id_320c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='idx_nr_user_read',
            old_name='notificatio_user_id_c217c7_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع الكائن المرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'إشعار عام'), ('course', 'إشعار مقرر'), ('file_upload', 'رفع ملف جديد'), ('assignment', 'واجب'), ('exam', 'اختبار'), ('grade', 'درجة'), ('announcement', 'إعلان'), ('system', 'إشعار نظام'), ('welcome', 'ترحيب')], default='general', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='حذف ناعم - الإشعار لا يظهر لكنه موجود', verbose_name='محذوف'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='idx_notif_type_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['course', 'created_at'], name='idx_notif_course_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', 'created_at'], name='idx_notif_sender_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_notif_generic'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'created_at'], name='idx_notif_active_date'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'is_read', 'is_deleted'], name='idx_nr_user_read_del'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'is_deleted', 'is_archived'], name='idx_nr_user_del_arch'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='file',
        ),
    ]
