# Generated by Django 6.0.2 on 2026-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False, help_text='المرسل نقل الإشعار إلى سلة المهملات', verbose_name='محذوف من المرسل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_hidden_by_sender',
            field=models.BooleanField(default=False, help_text='المرسل أخفى الإشعار من قائمته المرسلة', verbose_name='مخفي من المرسل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت حذف المرسل'),
        ),
    ]
